import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import { Button } from "reactstrap";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Agus Setiawan</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/aguss.png" />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css"
        />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className="hero d-lg-flex justify-content-center align-items-center position-lg-relative mt-5 flex-col-reverse flex-lg-row">
          <div
            className={`${styles.heroText} position-lg-relative sm text-lg-start`}
          >
            <h1 className={`z-2 ${styles.names}`}>
              My name is Agus Setiawan...
            </h1>
            <p id="typing" className={styles.typing}>
              Web Developer based in Indonesia
            </p>
            <Button
              variant="primary"
              href="/Contact"
              className={`${styles.btnHero}  btn mb-3`}
            >
              Let’s talk with me
            </Button>{" "}
          </div>

          <div
            className={`${styles.heroImg} position-relative d-none d-lg-block`}
          >
            <Image src={"/aguss.png"} alt="hero" width={500} height={500} />
          </div>
        </div>
      </main>
    </>
  );
}
